# Site settings
title: Blog
email: wdkrgst@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/mark" # the subpath of your site, e.g. /blog/
url: "http://www.dosrc.com" # the base hostname & protocol for your site
#twitter_username: vandykai
github_username:  vandykai

# Build settings
destination: ./_site/mark
markdown: kramdown
